#!/usr/bin/env python3
"""Convert NES ROM files to C byte arrays for embedding in firmware."""

import os
import sys
import re

ROM_DIR = os.path.join(os.path.dirname(__file__), '..', 'ROMs')
OUTPUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'rom_table.h')
MAX_SIZE = 1024 * 1024  # Skip ROMs > 1MB


def sanitize_name(filename):
    """Convert filename to a valid C identifier."""
    name = os.path.splitext(filename)[0]
    name = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    if name[0].isdigit():
        name = 'rom_' + name
    return name.lower()


def display_name(filename):
    """Create a human-readable display name from filename."""
    name = os.path.splitext(filename)[0]
    # Capitalize first letter, keep the rest as-is
    if name:
        name = name[0].upper() + name[1:]
    return name


def main():
    rom_files = sorted([f for f in os.listdir(ROM_DIR) if f.lower().endswith('.nes')])

    entries = []
    for fname in rom_files:
        path = os.path.join(ROM_DIR, fname)
        size = os.path.getsize(path)
        if size > MAX_SIZE:
            print(f"  Skipping {fname} ({size} bytes > {MAX_SIZE})")
            continue
        entries.append((fname, path, size))

    if not entries:
        print("No ROM files found!")
        sys.exit(1)

    print(f"Converting {len(entries)} ROMs to {OUTPUT}")

    with open(OUTPUT, 'w') as out:
        out.write("// Auto-generated by tools/convert_roms.py - DO NOT EDIT\n")
        out.write("#pragma once\n\n")
        out.write("#include <stdint.h>\n\n")

        # Write each ROM as a byte array
        for fname, path, size in entries:
            cname = sanitize_name(fname)
            print(f"  {fname} -> {cname} ({size} bytes)")

            with open(path, 'rb') as f:
                data = f.read()

            out.write(f"// {fname} ({size} bytes)\n")
            out.write(f"const unsigned char {cname}_data[] = {{\n")

            for i in range(0, len(data), 16):
                chunk = data[i:i+16]
                hex_str = ', '.join(f'0x{b:02x}' for b in chunk)
                out.write(f"  {hex_str},\n")

            out.write("};\n\n")

        # Write the ROM table struct and array
        out.write("struct rom_entry {\n")
        out.write("    const char* name;\n")
        out.write("    const unsigned char* data;\n")
        out.write("    unsigned int size;\n")
        out.write("};\n\n")

        out.write(f"#define ROM_COUNT {len(entries)}\n\n")

        out.write("const struct rom_entry rom_table[ROM_COUNT] = {\n")
        for fname, path, size in entries:
            cname = sanitize_name(fname)
            dname = display_name(fname)
            out.write(f'    {{ "{dname}", {cname}_data, sizeof({cname}_data) }},\n')
        out.write("};\n")

    total = sum(size for _, _, size in entries)
    print(f"Done! {len(entries)} ROMs, {total} bytes total ({total/1024:.1f} KB)")


if __name__ == '__main__':
    main()
